### ISSUE TITLE
Getting same error for all builds

### ISSUE THREAD

**Issue by ReYaNOW** [ndonkoHenri/flet-github-action-workflows#2]
Hello!
I am just forked Simple-Ethical-Counter repo and trying to run worflow

but getting [!] Android Studio (not installed) in builds for all platforms
Can you help me, please?

https://github.com/ReYaNOW/simple-ethical-counter/actions/runs/10655389892

```
Encountered error while archiving for device.
[[15:55:48](https://www.youtube.com/watch?v=ObO-D2TD_wo&t=57348s)] Deleting Flutter bootstrap directory                                 
           /var/folders/m4/5dz5h26x329cqq4fx333f8gm0000gn/T/flet_flutter_build_9
           zgeTKK9dp                                                            
           Error building Flet app - see the log of failed command above.       
           Run subprocess:                                                      
           ['/Users/runner/hostedtoolcache/flutter/stable-3.22.2-arm64/bin/flutt
           er', '--version']                                                    
[[15:55:49](https://www.youtube.com/watch?v=ObO-D2TD_wo&t=57349s)] Run subprocess:                                                      
           ['/Users/runner/hostedtoolcache/flutter/stable-3.22.2-arm64/bin/flutt
           er', 'doctor']                                                       
[[15:56:17](https://www.youtube.com/watch?v=ObO-D2TD_wo&t=57377s)] Doctor summary (to see all details, run flutter doctor -v):          
           [✓] Flutter (Channel stable, 3.22.2, on macOS 14.6.1 23G93           
           darwin-arm64, locale en-US)                                          
           [!] Android toolchain - develop for Android devices (Android SDK     
           version 35.0.0)                                                      
               ! Some Android licenses not accepted. To resolve this, run:      
           flutter doctor --android-licenses                                    
           [✓] Xcode - develop for iOS and macOS (Xcode 15.4)                   
           [✓] Chrome - develop for the web                                     
           [!] Android Studio (not installed)                                   
           [✓] Connected device (3 available)                                   
           [✓] Network resources      
```

**Comment by ReYaNOW** [comment]
I was able to fix this by changing
```
    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
```

to

```
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
```

and adding

```
    - name: Install Dependencies
      run: |
        sudo apt install ninja-build libgtk-3-dev
```

You can find full example [here](https://github.com/ReYaNOW/flet-build-test/blob/main/.github/workflows/build-apk.yml)
